import mongoose from 'mongoose';
const { Schema } = mongoose;

const ArtisanInsightSchema = new Schema({
  // Reference to the seller this insight belongs to
  seller: {
    type: Schema.Types.ObjectId,
    ref: 'Seller',
    required: true
  },
  // Growth plan generated by AI
  growthPlan: {
    type: String,
    default: ''
  },
  // AI-suggested product prices with reasoning
  suggestedPrices: [{
    productId: {
      type: Schema.Types.ObjectId,
      ref: 'Product'
    },
    price: Number,
    reasoning: String
  }],
  // Performance metrics for products
  productPerformance: [{
    productId: {
      type: Schema.Types.ObjectId,
      ref: 'Product'
    },
    sales: Number,
  }],
  // Data for the growth dashboard
  dashboardData: {
    type: Object,
    default: {}
  },
  lastUpdated: {
    type: Date,
    default: Date.now
  }
});

export default mongoose.model('ArtisanInsight', ArtisanInsightSchema);
